plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

packageExtensions:
  "babel-preset-react-app@*":
    dependencies:
      "@babel/plugin-proposal-private-property-in-object": "*"

pnpFallbackMode: dependencies-only

yarnPath: .yarn/releases/yarn-3.1.1.cjs
